### PR TITLE
add option to appeal both amount and penalty

### PR DESCRIPTION
**Pull request by axemonkey**
[Pivotal](https://www.pivotaltracker.com/story/show/133660223)

Add option to appeal against both the amount of tax owed and the penalty.

screen shot 2016-11-03 at 11 28 55

screen shot 2016-11-03 at 11 28 34

### CODE REVIEW

**Comment by axemonkey** [comment]
The copy I've used feels a bit pedestrian - maybe @joshlow can think of a better way to word this...

**Comment by mrbootle-moj** [comment]
@axemonkey @joshlow I'd say it should have "late return or payment" before penalty

**Comment by axemonkey** [comment]
@mrbootle-moj Like this? 
screen shot 2016-11-03 at 12 10 30

**Comment by axemonkey** [comment]
Deleting this branch and PR. As discussed, this option will now be covered by changing the "point of law" option to a "None of the above" option with free text entry.

**Pull request closed without merging**
