### PR TITLE
add option to appeal a point of law

### PR DESCRIPTION
**Pull request by axemonkey**
[Pivotal](https://www.pivotaltracker.com/story/show/133660303)

screen shot 2016-11-03 at 12 35 10

### CODE REVIEW

**Comment by mrbootle-moj** [comment]
@axemonkey I'm clarifying this with Alejandra as I'm not sure this is the correct place for this

**Comment by axemonkey** [comment]
@mrbootle-moj Righto. Standing by.

**Comment by mrbootle-moj** [comment]
@axemonkey I've spoken with Alejandra and this button should be written as "None of the above". Everything else remains the same.

**Comment by axemonkey** [comment]
@mrbootle-moj Sounds great.

Until, that is, you get to "check your answers"...

screen shot 2016-11-07 at 11 51 20

I guess maybe in this case we could simply not show the "What is your dispute about" line?

**Comment by mrbootle-moj** [comment]
@axemonkey good catch. Perhaps it might be better to put it as "Something else". Let's chat with @joshlow

**Comment by axemonkey** [comment]
Right, new version of this looks thus:

## dispute type

screen shot 2016-11-07 at 16 09 32

## fee screen

screen shot 2016-11-07 at 16 10 21

## check answers

screen shot 2016-11-07 at 16 11 00

**Comment by mrbootle-moj** [comment]
BAM!

**Comment by axemonkey** [comment]
merging!

**Pull request merged**
